### ISSUE TITLE
RAM

### ISSUE THREAD

**Issue by lyranie** [y2k04/dls-circuits#1]
RAM
> by neariyeveryone
---

![Screenshot 2023-03-04 052900](https://user-images.githubusercontent.com/103459091/222875671-634420c8-9b21-4fc5-8d59-7abc918060ef.png)

[RAM.zip](https://github.com/y2k04/dls-circuits/files/10887463/RAM.zip)

**Comment by lyranie** [comment]
idk how you wanna implement this but i put all the required subchips into the zip aswell

**Comment by y2k04** [comment]
> idk how you wanna implement this but i put all the required subchips into the zip aswell

I noticed :3
Thank you!

**Comment by lyranie** [comment]
and in order for it to show up in your project the name has to be added to the ProjectSettings.json into the "AllCreatedChips" and "StarredChips" list

**Comment by y2k04** [comment]
Yeah
