### ISSUE TITLE
Double Dabble

### ISSUE THREAD

**Issue by lyranie** [y2k04/dls-circuits#2]
Double Dabble
> by neariyeveryone
---

![Screenshot 2023-03-04 053151](https://user-images.githubusercontent.com/103459091/222875764-2ac081fc-5853-4709-a400-eeac1f0057b7.png)

use case example:
![Screenshot 2023-03-04 071446](https://user-images.githubusercontent.com/103459091/222879458-94ca4f77-760f-42d9-bf26-8fdbb99093f1.png)

[DOUBLE DABBLE.zip](https://github.com/y2k04/dls-circuits/files/10887466/DOUBLE.DABBLE.zip)

**Comment by y2k04** [comment]
Added
