### ISSUE TITLE
Display Driver

### ISSUE THREAD

**Issue by lyranie** [y2k04/dls-circuits#3]
Display Driver
> by neariyeveryone
---

![Screenshot 2023-03-04 061703](https://user-images.githubusercontent.com/103459091/222877384-817d04a8-0516-419d-b65b-7eb81d7e0abe.png)

use case example:
![Screenshot 2023-03-04 071446](https://user-images.githubusercontent.com/103459091/222879458-94ca4f77-760f-42d9-bf26-8fdbb99093f1.png)

[DISPLAY DRIVER.zip](https://github.com/y2k04/dls-circuits/files/10887521/DISPLAY.DRIVER.zip)

**Comment by y2k04** [comment]
Added
